name: Deploy Rspress site to Pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Not needed if lastUpdated is not enabled
    - uses: pnpm/action-setup@v3 # pnpm is optional but recommended, you can also use npm / yarn
      with:
        version: 9
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Format code
      run: pnpm run fmt
    - name: Build with Rspress
      run: |
        pnpm run build
